---

- name: Export 'credential_types'
  awx.awx.export:
    controller_host: "{{ tower_awx[awx_type][awx_env]['url'] }}"
    controller_username: "{{ tower_awx[awx_type][awx_env]['api_user'] if awx_token is undefined else omit }}"
    controller_password: "{{ tower_awx[awx_type][awx_env]['api_password'] if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ tower_awx[awx_type][awx_env]['validate_certs'] }}"

    credential_types: all

  register: _awx_credential_types
  delegate_to: "{{ execution_host | default(omit) }}"

- name: Write 'credential_types' to file
  ansible.builtin.copy:
    content: "{{ _awx_credential_types | to_nice_json }}"
    dest: "{{ awx_export_path + '/credential_types.json' }}"
    mode: "0640"
  delegate_to: localhost
  connection: local
