---

- name: Export 'inventory'
  awx.awx.export:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"
    inventory: all
  register: _awx_inventory
  delegate_to: "{{ execution_host | default(omit) }}"

- name: Write 'inventory' to file
  ansible.builtin.copy:
    content: "{{ _awx_inventory | to_nice_json }}"
    dest: "{{ awx_export_path + '/inventory.json' }}"
    mode: "0640"
  delegate_to: localhost
  connection: local
