---

- name: Export 'job_templates'
  awx.awx.export:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"
    job_templates: all
  register: _awx_job_templates
  delegate_to: "{{ execution_host | default(omit) }}"

- name: Write 'job_templates' to file
  ansible.builtin.copy:
    content: "{{ _awx_job_templates | to_nice_json }}"
    dest: "{{ awx_export_path + '/job_templates.json' }}"
    mode: "0640"
  delegate_to: localhost
  connection: local
