---

- name: Set different python interpreter for AWX/Tower
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ awx_python_interpreter }}"
  when: awx_python_interpreter is defined

- name: Asserts
  ansible.builtin.assert:
    that:
      - awx_export_path is defined

- name: Create export path
  ansible.builtin.file:
    path: "{{ awx_export_path }}"
    state: directory
    mode: "0700"
  delegate_to: "{{ awx_execution_host }}"

- name: Obtain token
  ansible.builtin.include_tasks:
    file: token.yml

- name: Export all resources
  ansible.builtin.include_tasks:
    file: "{{ awx_resource }}.yml"
  loop: "{{ awx_export_resources }}"
  loop_control:
    loop_var: awx_resource
