---

- name: Export 'projects'
  awx.awx.export:
    controller_host: "{{ awx_url }}"
    controller_username: "{{ awx_username if awx_token is undefined else omit }}"
    controller_password: "{{ awx_password if awx_token is undefined else omit }}"
    controller_oauthtoken: "{{ awx_token | default(omit) }}"
    validate_certs: "{{ awx_verify_ssl }}"
    projects: all
  register: _awx_projects
  delegate_to: "{{ execution_host | default(omit) }}"

- name: Write 'projects' to file
  ansible.builtin.copy:
    content: "{{ _awx_projects | to_nice_json }}"
    dest: "{{ awx_export_path + '/projects.json' }}"
    mode: "0640"
  delegate_to: localhost
  connection: local
