---

- name: Export 'system_job_templates'
  ansible.builtin.command: >-
    {{ awx_command }} system_job_templates list --all
  environment:
    TOWER_HOST: "{{ awx_url }}"
    TOWER_USERNAME: "{{ awx_username if awx_token is undefined else omit }}"
    TOWER_PASSWORD: "{{ awx_password if awx_token is undefined else omit }}"
    TOWER_OAUTH_TOKEN: "{{ awx_token | default(omit) }}"
    TOWER_VERIFY_SSL: "{{ awx_verify_ssl }}"
  changed_when: false
  register: _awx_system_job_templates
  delegate_to: "{{ execution_host | default(omit) }}"

- name: Write 'system_job_templates' to file
  ansible.builtin.copy:
    content: "{{ _awx_system_job_templates.stdout | from_json | json_query('results') | to_nice_json }}"
    dest: "{{ awx_export_path + '/system_job_templates.json' }}"
    mode: "0640"
  delegate_to: localhost
  connection: local
