---

- name: Retrieve Oauth2 token
  ansible.builtin.command: >-
    {{ awx_command }} login
  environment:
    TOWER_HOST: "{{ awx_url }}"
    TOWER_USERNAME: "{{ awx_username if awx_token is undefined else omit }}"
    TOWER_PASSWORD: "{{ awx_password if awx_token is undefined else omit }}"
    TOWER_VERIFY_SSL: "{{ awx_verify_ssl }}"
  changed_when: false
  register: _awx_oauth

- name: Save token
  ansible.builtin.set_fact:
    awx_token: "{{ _awx_oauth.stdout | from_json | json_query('token') }}"
