---

- name: Converge pre playbook
  ansible.builtin.import_playbook: converge-pre.yml

- name: Converge
  hosts: all
  become: "no"
  vars:
    awx_command: /usr/local/bin/awx
    awx_export_path: /tmp/awx
  tasks:
    - name: Include role 'ansible-role-awx_export'
      ansible.builtin.include_role:
        name: ansible-role-awx_export
