---

- name: Converge pre playbook
  ansible.builtin.import_playbook: converge-pre.yml
  when: molecule_converge_pre is undefined or molecule_converge_pre | bool

- name: Converge
  hosts: all
  become: "no"
  vars:
    molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"
    awx_command: /usr/local/bin/awx
    awx_export_path: /tmp/awx
    awx_url: https://127.0.0.1
    awx_username: admin
    awx_password: Admin123!
    awx_verify_ssl: False
  tasks:
    - name: Include role 'ansible-role-awx_export'
      ansible.builtin.include_role:
        name: ansible-role-awx_export
